pipeline {
    agent any

    stages {
        stage('Init') {
            steps {
                echo 'Initializing..'
                sh'apt-get update'
                sh'apt-get install python3 -y'
                sh'apt-get install python3-pip -y'
                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
            }
        }
        stage('Test') {
            steps {
                dir('/aula_3') {
                //sh'python -m pip install --upgrade pip'
                //sh'pip install -r requirements.txt'
                sh'pip install -r .aula_3/app/requirements.txt --break-system-packages'
                sh'pip install pylint -y'
                sh'pylint --ignore-patterns "test.*py" ./aula_3/app'
                sh'pip install pytest -y'
                sh'pytest'
            }
               // echo 'testador de codigo..'
                //echo 'executando o pytest..'
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                echo 'Running docker build -t sntshk/cotu .'
            }
        }
        stage('Publish') {
            steps {
                echo 'Publishing..'
                echo 'Running docker push..'
            }
        }
        stage('Cleanup') {
            steps {
                echo 'Cleaning..'
                echo 'Running docker rmi..'
            }
        }
    }
}
