on:
  workflow_dispatch:
    inputs:
      project:
        description: "Project Name"
        required: true
        default: "ada_pipelines_maio"
      repositoryName:
        description: "Repository Name"
        type: string
        required: true
      grupoRevisores:
        description: "Nome do grupo de revisores"
        required: true
        type: choice
        default: "Contributors"
        options:
          - DevOps
          - Contributors
          - CreditoTeam

name: "Create Azure DevOps Repository"

jobs:
  create-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v2
        name: Setup Terraform

      - name: "Terraform Init"
        run: terraform init
        working-directory: ./aula_5/terraform

      - name: "Terraform Init"
        run: terraform apply -auto-approve -var="repository_name=${{ inputs.repositoryName }}"
        working-directory: ./aula_5/terraform
        env:
          AZDO_ORG_SERVICE_URL: ${{ vars.AZDO_ORG_SERVICE_URL }}
          AZDO_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZDO_PERSONAL_ACCESS_TOKEN }}
          TF_VAR_project_name: ${{ inputs.project }}
